### ISSUE TITLE
lghub_installer install failed

### ISSUE THREAD

**Issue by callmegaga** [BoranCanOzel/bf1-external#2]
I am very exciting to found this project.But I can't install the GHUB with your lghub_installer_2021.11.8744.exe sofrware.My OS is Win11 23H2,I will got a  Installation Failed error.Can I install other version GHUB,or support other mouse software?

**Comment by BoranCanOzel** [comment]
Hi there,

Thank you for your interest in the project and for reaching out with your issue. Unfortunately, I cannot guarantee that other versions of GHUB will work, as this particular method was developed with a specific version that contains the necessary features for our approach.

However, you have the option to modify the mouse emulation method to support different mouse software or use a mouse library of your choice. Since this is an open-source project, feel free to adjust the source code to accommodate any mouse software that is compatible with your system. If you have any more questions or need further assistance, please let me know!

Best regards,
BoranCanOzel
